// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// Chill_Cpp
double Chill_Cpp(DoubleVector temp);
RcppExport SEXP _miniChill_Chill_Cpp(SEXP tempSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DoubleVector >::type temp(tempSEXP);
    rcpp_result_gen = Rcpp::wrap(Chill_Cpp(temp));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_hello_world
List rcpp_hello_world();
RcppExport SEXP _miniChill_rcpp_hello_world() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpp_hello_world());
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_miniChill_Chill_Cpp", (DL_FUNC) &_miniChill_Chill_Cpp, 1},
    {"_miniChill_rcpp_hello_world", (DL_FUNC) &_miniChill_rcpp_hello_world, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_miniChill(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
