# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Chill portion calculator
#' 
#' \code{chill_func} returns the chill portion count of a temperature vector
#' 
#' @param temp a vector of temperautres \emph{in Celsius}
#' 
#' @return The output is the chill portion calculation. Portions are rounded
#' down to the largest integer.
#' @export
#' 
NULL

chill_func <- function(temp) {
    .Call(`_miniChill_chill_func`, temp)
}

