# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Chill portion calculator
#' 
#' \code{chill_func} returns the chill portion count of a temperature vector
#' 
#' @param temp a vector of temperautres \emph{in Celsius}
#' 
#' @return The output is the chill portion calculation. Portions are rounded
#' down to the largest integer.
NULL

Chill_Cpp <- function(temp) {
    .Call(`_miniChill_Chill_Cpp`, temp)
}

rcpp_hello_world <- function() {
    .Call(`_miniChill_rcpp_hello_world`)
}

